/** Khám phá Toán 2 Tập Một: bài → mục (định dạng ở lessonHelp.js). Nội dung chạy ở ./index.js (tải khi bấm). */
const x = (n, title) => ({ key: `b${n}`, title: `Bài ${n}: ${title}` });

export const EXPLORE_MAP = {
  1: [x(1, 'Ôn tập các số đến 100')],
  2: [x(2, 'Tia số. Số liền trước, số liền sau')],
  3: [x(3, 'Các thành phần của phép cộng, phép trừ')],
  4: [x(4, 'Hơn, kém nhau bao nhiêu')],
  5: [x(5, 'Ôn tập phép cộng, phép trừ (không nhớ)')],
  6: [{ see: 4, when: /hơn|kém/i }, { see: 5 }, { see: 1 }],
  7: [x(7, 'Phép cộng (qua 10) trong phạm vi 20')],
  8: [x(8, 'Bảng cộng (qua 10)')],
  9: [x(9, 'Bài toán về thêm, bớt một số đơn vị')],
  10: [{ see: 9, when: /Hỏi|bán|thêm|bớt/ }, { see: 7 }, { see: 8 }],
  11: [x(11, 'Phép trừ (qua 10) trong phạm vi 20')],
  12: [x(12, 'Bảng trừ (qua 10)')],
  13: [x(13, 'Bài toán về nhiều hơn, ít hơn một số đơn vị')],
  14: [{ see: 13, when: /nhiều hơn|ít hơn/ }, { see: 9, when: /Hỏi|biếu|thêm|bớt/ }, { see: 11 }, { see: 12 }, { see: 8 }],
  15: [x(15, 'Ki-lô-gam')],
  16: [x(16, 'Lít')],
  17: [{ see: 15, when: /kg|ki-lô-gam|nặng|nhẹ|cân/i }, { see: 16, when: /lít|\bl\b|cốc|bình|ca\b|nước/i }, { see: 15 }, { see: 16 }],
  18: [{ see: 15, when: /kg|ki-lô-gam|nặng|nhẹ|cân|gạo/i }, { see: 16, when: /lít|\bl\b|cốc|bình|nước/i }, { see: 15 }, { see: 16 }],
  19: [x(19, 'Phép cộng (có nhớ) số có hai chữ số với số có một chữ số')],
  20: [x(20, 'Phép cộng (có nhớ) số có hai chữ số với số có hai chữ số')],
  21: [{ see: 20 }, { see: 19 }],
  22: [x(22, 'Phép trừ (có nhớ) số có hai chữ số cho số có một chữ số')],
  23: [x(23, 'Phép trừ (có nhớ) số có hai chữ số cho số có hai chữ số')],
  24: [{ see: 23 }, { see: 22 }],
  25: [x(25, 'Điểm, đoạn thẳng, đường thẳng, đường cong')],
  26: [x(26, 'Đường gấp khúc. Hình tứ giác')],
  27: [x(27, 'Ghép hình. Vẽ đoạn thẳng')],
  28: [{ see: 26, when: /gấp khúc|tứ giác|bò/i }, { see: 25 }, { see: 26 }],
  29: [x(29, 'Ngày – giờ, giờ – phút')],
  30: [x(30, 'Ngày – tháng')],
  31: [{ see: 30, when: /lịch|tháng|ngày/i }, { see: 29, when: /đồng hồ|giờ|phút/i }, { see: 29 }, { see: 30 }],
  32: [{ see: 30, when: /lịch|tháng|ngày/i }, { see: 29, when: /đồng hồ|giờ|phút/i }, { see: 29 }, { see: 30 }],
  33: [
    { see: 20, when: /Đặt tính|\d\d \+ \d\d/ }, { see: 23, when: /Đặt tính|\d\d [−-] \d\d/ },
    { see: 15, when: /cân|túi|kg/i }, { see: 13, when: /nhiều hơn|ít hơn/ },
    { see: 7, when: /Tính nhẩm|Số\?|dưa|hoa/ }, { see: 11, when: /Tính nhẩm|Số\?|dưa|hoa/ }, { see: 8 }, { see: 12 },
  ],
  34: [
    { see: 25, when: /thẳng hàng|điểm|đoạn thẳng|đường thẳng|đường cong/i }, { see: 26, when: /tứ giác|gấp khúc/i },
    { see: 27, when: /ghép|xếp|vẽ/i }, { see: 25 }, { see: 26 },
  ],
  35: [
    { see: 15, when: /kg|ki-lô-gam|nặng|nhẹ|cân|dê/i }, { see: 16, when: /lít|<i>l<\/i>|\bl\b|bình|ca\b|can|thùng|nước/i },
    { see: 13, when: /nhiều hơn|ít hơn|nhẹ hơn/ }, { see: 15 }, { see: 16 },
  ],
  36: [
    { see: 29, when: /đồng hồ|giờ|phút/i }, { see: 20, when: /Đặt tính/ }, { see: 23, when: /Đặt tính/ },
    { see: 15, when: /kg|ki-lô-gam|nặng|cân/i }, { see: 16, when: /lít|<i>l<\/i>|\bl\b|can|ca\b|nước/i },
    { see: 26, when: /đường|kiến|gấp khúc/i }, { see: 13, when: /nhiều hơn|ít hơn|nặng hơn/ }, { see: 20 }, { see: 23 },
  ],
};
